---
 - name: Remove swapfile from /etc/fstab
   mount:
     name: swap
     fstype: swap
     state: absent

 - name: Turn swap off
   shell: swapoff -a

 - name: setenforce
   command: setenforce 0 

 - name: change selinux permissive
   command: sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
   
 - name: Add netbridge config ip6
   lineinfile:
     path: /etc/sysctl.d/k8s.conf
     line: 'net.bridge.bridge-nf-call-ip6tables = 1'
     state: present
     create: yes

 - name: Add netbridge config ip4
   lineinfile:
     path: /etc/sysctl.d/k8s.conf
     line: 'net.bridge.bridge-nf-call-iptables = 1'
     state: present
     create: yes

 - name: update sysctl
   command: sysctl --system
   
 - name: Enable packet forwarding
   command: echo 1 > /proc/sys/net/ipv4/ip_forward