---
 - name: install kubernetes packages
   yum:
     name: "{{item}}"
   with_items:
     - kubelet-{{kubelet_version}}
     - kubeadm-{{kubeadm_version}}
     - kubectl-{{kubectl_version}}
     
 - name: enable kubelet
   systemd: 
     name: kubelet
     enabled: yes
