---
 - name: installing etcd for all masters
   yum:
     name: etcd
     state: latest

 - name: copying etcd.service to all masters
   template:
     src: etcd.service 
     dest: /etc/systemd/system/etcd.service

 - name: starting etcd 
   systemd:
     name: etcd
     state: started
     enabled: yes
     daemon_reload: yes

