 - import_playbook: etc-hosts-entry.yaml
 - import_playbook: add-repository.yaml
 - import_playbook: docker-setup.yaml
 - import_playbook: pre-requisities-kubeadm.yaml
 - import_playbook: kubernetes-setup.yaml
 - import_playbook: firewall-setup.yaml
 - import_playbook: cfssl-setup.yaml
 - import_playbook: generate-etcd-certs.yaml
 - import_playbook: etcd-prerequisite.yaml
 - import_playbook: etcd-setup.yaml
 - import_playbook: keepalived.yaml
 - import_playbook: kubeadm-init-prep.yaml
 - import_playbook: kubeadm-init-first-master.yaml
 - import_playbook: kubeadm-init-other-master.yaml
 - import_playbook: insecure-registry.yaml
 - import_playbook: calico.yaml
 - import_playbook: metallb-setup.yaml
 - import_playbook: contour-setup.yaml

